### ISSUE TITLE
LSP-tailwindcss

### ISSUE THREAD

**Issue by asmeeee** [SublimeText/TailwindCSS#2]
Hey! Should we use this package together with https://github.com/sublimelsp/LSP-tailwindcss or should we just use `LSP-tailwindcss`?

**Comment by deathaxe** [comment]
This package provides a syntax definition which is based on ST's default CSS and adds Tailwind related @-rules. ST's default CSS fails to highlight those addtional tags. So if you don't have another 3rd-party CSS syntax which is able to highlight tailwind, you might want to use this package.

LSP-tailwindcss on the other hand is a helper plugin for LSP package which may be used to provide auto-completions etc. but it doesn't provide syntax highlighting.

**Comment by asmeeee** [comment]
> This package provides a syntax definition which is based on ST's default CSS and adds Tailwind related @-rules. ST's default CSS fails to highlight those addtional tags. So if you don't have another 3rd-party CSS syntax which is able to highlight tailwind, you might want to use this package.
> 
> LSP-tailwindcss on the other hand is a helper plugin for LSP package which may be used to provide auto-completions etc. but it doesn't provide syntax highlighting.

Thank you!
