### ISSUE TITLE
No support for tailwindcss/nesting

### ISSUE THREAD

**Issue by jnns** [SublimeText/TailwindCSS#5]
There's no support for nested declarations yet, is there? At least they don't seem to be recognized as such on my screenshot:
![grafik](https://user-images.githubusercontent.com/206281/136232865-f299bdbd-c002-4adb-948b-374d144ef3a1.png)

The TailwindCSS docs say this about the [nested plugin](https://tailwindcss.com/docs/using-with-preprocessors#nesting):

> To add support for nested declarations, we recommend our bundled tailwindcss/nesting plugin, which is a PostCSS plugin that wraps postcss-nested or postcss-nesting and acts as a compatibility layer to make sure your nesting plugin of choice properly understands Tailwind’s custom syntax like @apply and @screen.
>
> It’s included directly in the tailwindcss package itself, so to use it all you need to do is add it to your PostCSS configuration, somewhere before Tailwind

**Comment by deathaxe** [comment]
This syntax extends default CSS syntax shipped with ST, which doesn't support nesting.

**Comment by zigi05** [comment]
@deathaxe is it possible to add highlighting rules for nested declarations in your extending file? Would be also very useful for those who use Sass.

I've tried to make my own syntax extension, but can't quite grasp it for the lack of online tutorials and documentation that is hard for me to follow.

**Comment by deathaxe** [comment]
Haven't investigated what it means to add nexting support to ST's core CSS syntax. Anyway nested CSS selectors are not the same as supporting SASS/SCSS, because the former require `&` operator to start selectors while SASS/SCSS doen't need that.

**Comment by zigi05** [comment]
I guess sass/scss rules can be borrowed from [here](https://github.com/braver/SublimeSass/blob/master/Syntaxes/Sass.sublime-syntax) and implemented properly in tailwind syntax extension file. I tried doing it myself, but couldn't understand how to make it work.

**Comment by deathaxe** [comment]
SASS requires some more extensions than just nested properties. The linked package uses quite different syntax design than normal CSS and it is not within the scope of this Package. This package just adds the relevant at-rules to the existing default CSS syntax.

**Comment by jnns** [comment]
There's [a draft for native nesting in CSS](https://drafts.csswg.org/css-nesting-1/) as well. [Here's a blog post about it](https://kilianvalkhof.com/2021/css-html/css-nesting-specificity-and-you/). Eventually the CSS syntax that Sublime Text ships with will have to support it too, I assume. 

Would it make sense to ask for support upstream? All syntax definitions inheriting from the base syntax would benefit from it.

**Comment by deathaxe** [comment]
Traditionally ST doesn't support non-standard features.

v1.1.0 adds support for the PostCSS style nesting using the `&` operator.

SCSS/LESS style nesting - as requested by this issue - is still out of scope.

**Comment by jnns** [comment]
Thank you very much for implementing the `&` operator @deathaxe!

Now I'm not distracted by red syntax highlighting anymore
![grafik](https://user-images.githubusercontent.com/206281/151948449-07683d3c-2d61-421b-aca8-17f503f6130c.png)

The SCSS/LESS style nesting is not something I personally would need to see implemented as native CSS nesting requires the `&` operator. Please feel free to close this issue.

**Comment by deathaxe** [comment]
OK, thank's for the feedback.
