### ISSUE TITLE
SublimeMerge: missing variable combinator_char

### ISSUE THREAD

**Issue by dpslwk** [SublimeText/TailwindCSS#8]
Im getting this error thrown by SublimeMerge ever so offten

`Error loading syntax file "Packages/Tailwind CSS/Tailwind CSS.sublime-syntax": missing variable combinator_char`

<img width="261" alt="Screenshot 2023-08-21 at 21 46 10" src="https://github.com/SublimeText/TailwindCSS/assets/234460/47f2f417-9326-42e2-a6d3-06c1f98f3f1d">

not sure if this should be an issue here of over at https://github.com/sublimehq/sublime_merge/

**Comment by deathaxe** [comment]
Tailwind CSS extends ST's CSS syntax and so extends SM's CSS when loaded by Sublime Merge.

The `combinator_char` variable was added by https://github.com/sublimehq/Packages/pull/3717 and is shipped with ST4149+. It is therefore also part of latest stable ST4152.

In that case Tailwind CSS package is installed from `master` branch (or 4149-... tag).

Current Sublime Merge stable release however does not include mentioned PR and thus, ST's variant of Tailwind CSS is not compatible.

As Sublime Merge just loads all 3rd-party syntaxes from ST installation, there's no solution a package can ensure compatibility for both applications individually.

You can either update to latest Sublime Merge dev build or copy ST's CSS.sublime-package over to Sublime Merge.

**Comment by deathaxe** [comment]
Sublime Merge 2091 has been released, which should fix the issue.
